package myfan.data.models;
// Generated Jun 17, 2016 12:28:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Artists generated by hbm2java
 */
public class Artists implements java.io.Serializable {

  private Integer artistId;
  private Users users;
  private int followers;
  private String bio;
  private Set<FanaticsArtists> fanaticsArtistses = new HashSet<FanaticsArtists>(0);
  private Set<ArtistsCalifications> artistsCalificationses = new HashSet<ArtistsCalifications>(0);
  private Set<News> newses = new HashSet<News>(0);
  private Set<Members> memberses = new HashSet<Members>(0);
  private Set<Events> eventses = new HashSet<Events>(0);
  private Set<Discs> discses = new HashSet<Discs>(0);

  public Artists() {
  }

  public Artists(Users users, int followers, String bio) {
    this.users = users;
    this.followers = followers;
    this.bio = bio;
  }

  public Artists(Users users, int followers, String bio, Set<FanaticsArtists> fanaticsArtistses,
      Set<ArtistsCalifications> artistsCalificationses, Set<News> newses, Set<Members> memberses, Set<Events> eventses,
      Set<Discs> discses) {
    this.users = users;
    this.followers = followers;
    this.bio = bio;
    this.fanaticsArtistses = fanaticsArtistses;
    this.artistsCalificationses = artistsCalificationses;
    this.newses = newses;
    this.memberses = memberses;
    this.eventses = eventses;
    this.discses = discses;
  }

  public Integer getArtistId() {
    return this.artistId;
  }

  public void setArtistId(Integer artistId) {
    this.artistId = artistId;
  }

  public Users getUsers() {
    return this.users;
  }

  public void setUsers(Users users) {
    this.users = users;
  }

  public int getFollowers() {
    return this.followers;
  }

  public void setFollowers(int followers) {
    this.followers = followers;
  }

  public String getBio() {
    return this.bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public Set<FanaticsArtists> getFanaticsArtistses() {
    return this.fanaticsArtistses;
  }

  public void setFanaticsArtistses(Set<FanaticsArtists> fanaticsArtistses) {
    this.fanaticsArtistses = fanaticsArtistses;
  }

  public Set<ArtistsCalifications> getArtistsCalificationses() {
    return this.artistsCalificationses;
  }

  public void setArtistsCalificationses(Set<ArtistsCalifications> artistsCalificationses) {
    this.artistsCalificationses = artistsCalificationses;
  }

  public Set<News> getNewses() {
    return this.newses;
  }

  public void setNewses(Set<News> newses) {
    this.newses = newses;
  }

  public Set<Members> getMemberses() {
    return this.memberses;
  }

  public void setMemberses(Set<Members> memberses) {
    this.memberses = memberses;
  }

  public Set<Events> getEventses() {
    return this.eventses;
  }

  public void setEventses(Set<Events> eventses) {
    this.eventses = eventses;
  }

  public Set<Discs> getDiscses() {
    return this.discses;
  }

  public void setDiscses(Set<Discs> discses) {
    this.discses = discses;
  }

}
