package myfan.data.models;
// Generated Jun 13, 2016 12:10:00 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Artists generated by hbm2java
 */
public class Artists implements java.io.Serializable {

  private Integer artistId;
  private Users users;
  private int followers;
  private Set artistsCalificationses = new HashSet(0);
  private Set newses = new HashSet(0);
  private Set memberses = new HashSet(0);
  private Set eventses = new HashSet(0);
  private Set discses = new HashSet(0);

  public Artists() {
  }

  public Artists(Users users, int followers) {
    this.users = users;
    this.followers = followers;
  }

  public Artists(Users users, int followers, Set artistsCalificationses, Set newses, Set memberses, Set eventses,
      Set discses) {
    this.users = users;
    this.followers = followers;
    this.artistsCalificationses = artistsCalificationses;
    this.newses = newses;
    this.memberses = memberses;
    this.eventses = eventses;
    this.discses = discses;
  }

  public Integer getArtistId() {
    return this.artistId;
  }

  public void setArtistId(Integer artistId) {
    this.artistId = artistId;
  }

  public Users getUsers() {
    return this.users;
  }

  public void setUsers(Users users) {
    this.users = users;
  }

  public int getFollowers() {
    return this.followers;
  }

  public void setFollowers(int followers) {
    this.followers = followers;
  }

  public Set getArtistsCalificationses() {
    return this.artistsCalificationses;
  }

  public void setArtistsCalificationses(Set artistsCalificationses) {
    this.artistsCalificationses = artistsCalificationses;
  }

  public Set getNewses() {
    return this.newses;
  }

  public void setNewses(Set newses) {
    this.newses = newses;
  }

  public Set getMemberses() {
    return this.memberses;
  }

  public void setMemberses(Set memberses) {
    this.memberses = memberses;
  }

  public Set getEventses() {
    return this.eventses;
  }

  public void setEventses(Set eventses) {
    this.eventses = eventses;
  }

  public Set getDiscses() {
    return this.discses;
  }

  public void setDiscses(Set discses) {
    this.discses = discses;
  }

}
