package myfan.data.models;
// Generated May 29, 2016 3:37:51 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * DiscsCalifications generated by hbm2java
 */
public class DiscsCalifications implements java.io.Serializable {

  private int discCalificationId;
  private Discs discs;
  private int calification;
  private String comment;

  public DiscsCalifications() {
  }

  public DiscsCalifications(int discCalificationId, Discs discs, int calification) {
    this.discCalificationId = discCalificationId;
    this.discs = discs;
    this.calification = calification;
  }

  public DiscsCalifications(int discCalificationId, Discs discs, int calification, String comment) {
    this.discCalificationId = discCalificationId;
    this.discs = discs;
    this.calification = calification;
    this.comment = comment;
  }

  public int getDiscCalificationId() {
    return this.discCalificationId;
  }

  public void setDiscCalificationId(int discCalificationId) {
    this.discCalificationId = discCalificationId;
  }

  public Discs getDiscs() {
    return this.discs;
  }

  public void setDiscs(Discs discs) {
    this.discs = discs;
  }

  public int getCalification() {
    return this.calification;
  }

  public void setCalification(int calification) {
    this.calification = calification;
  }

  public String getComment() {
    return this.comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

}
