package myfan.data.models;
// Generated Jun 13, 2016 12:10:00 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * DiscsCalifications generated by hbm2java
 */
public class DiscsCalifications implements java.io.Serializable {

  private Integer discCalificationId;
  private Discs discs;
  private Fanatics fanatics;
  private int calification;
  private String comment;

  public DiscsCalifications() {
  }

  public DiscsCalifications(Discs discs, int calification) {
    this.discs = discs;
    this.calification = calification;
  }

  public DiscsCalifications(Discs discs, Fanatics fanatics, int calification, String comment) {
    this.discs = discs;
    this.fanatics = fanatics;
    this.calification = calification;
    this.comment = comment;
  }

  public Integer getDiscCalificationId() {
    return this.discCalificationId;
  }

  public void setDiscCalificationId(Integer discCalificationId) {
    this.discCalificationId = discCalificationId;
  }

  public Discs getDiscs() {
    return this.discs;
  }

  public void setDiscs(Discs discs) {
    this.discs = discs;
  }

  public Fanatics getFanatics() {
    return this.fanatics;
  }

  public void setFanatics(Fanatics fanatics) {
    this.fanatics = fanatics;
  }

  public int getCalification() {
    return this.calification;
  }

  public void setCalification(int calification) {
    this.calification = calification;
  }

  public String getComment() {
    return this.comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

}
