package myfan.data.models;
// Generated Jun 17, 2016 12:28:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Discs generated by hbm2java
 */
public class Discs implements java.io.Serializable {

  private Integer discId;
  private Artists artists;
  private Genres genres;
  private String name;
  private String description;
  private Date releaseYear;
  private String label;
  private Set<DiscsCalifications> discsCalificationses = new HashSet<DiscsCalifications>(0);
  private Set<Songs> songses = new HashSet<Songs>(0);

  public Discs() {
  }

  public Discs(Artists artists, Genres genres, String name, Date releaseYear) {
    this.artists = artists;
    this.genres = genres;
    this.name = name;
    this.releaseYear = releaseYear;
  }

  public Discs(Artists artists, Genres genres, String name, String description, Date releaseYear, String label,
      Set<DiscsCalifications> discsCalificationses, Set<Songs> songses) {
    this.artists = artists;
    this.genres = genres;
    this.name = name;
    this.description = description;
    this.releaseYear = releaseYear;
    this.label = label;
    this.discsCalificationses = discsCalificationses;
    this.songses = songses;
  }

  public Integer getDiscId() {
    return this.discId;
  }

  public void setDiscId(Integer discId) {
    this.discId = discId;
  }

  public Artists getArtists() {
    return this.artists;
  }

  public void setArtists(Artists artists) {
    this.artists = artists;
  }

  public Genres getGenres() {
    return this.genres;
  }

  public void setGenres(Genres genres) {
    this.genres = genres;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Date getReleaseYear() {
    return this.releaseYear;
  }

  public void setReleaseYear(Date releaseYear) {
    this.releaseYear = releaseYear;
  }

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Set<DiscsCalifications> getDiscsCalificationses() {
    return this.discsCalificationses;
  }

  public void setDiscsCalificationses(Set<DiscsCalifications> discsCalificationses) {
    this.discsCalificationses = discsCalificationses;
  }

  public Set<Songs> getSongses() {
    return this.songses;
  }

  public void setSongses(Set<Songs> songses) {
    this.songses = songses;
  }

}
