package myfan.data.models;
// Generated Jun 17, 2016 12:28:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Fanatics generated by hbm2java
 */
public class Fanatics implements java.io.Serializable {

  private Integer fanaticId;
  private Users users;
  private boolean sex;
  private Set<EventsCalifications> eventsCalificationses = new HashSet<EventsCalifications>(0);
  private Set<ArtistsCalifications> artistsCalificationses = new HashSet<ArtistsCalifications>(0);
  private Set<FanaticsArtists> fanaticsArtistses = new HashSet<FanaticsArtists>(0);
  private Set<DiscsCalifications> discsCalificationses = new HashSet<DiscsCalifications>(0);

  public Fanatics() {
  }

  public Fanatics(Users users, boolean sex) {
    this.users = users;
    this.sex = sex;
  }

  public Fanatics(Users users, boolean sex, Set<EventsCalifications> eventsCalificationses,
      Set<ArtistsCalifications> artistsCalificationses, Set<FanaticsArtists> fanaticsArtistses,
      Set<DiscsCalifications> discsCalificationses) {
    this.users = users;
    this.sex = sex;
    this.eventsCalificationses = eventsCalificationses;
    this.artistsCalificationses = artistsCalificationses;
    this.fanaticsArtistses = fanaticsArtistses;
    this.discsCalificationses = discsCalificationses;
  }

  public Integer getFanaticId() {
    return this.fanaticId;
  }

  public void setFanaticId(Integer fanaticId) {
    this.fanaticId = fanaticId;
  }

  public Users getUsers() {
    return this.users;
  }

  public void setUsers(Users users) {
    this.users = users;
  }

  public boolean isSex() {
    return this.sex;
  }

  public void setSex(boolean sex) {
    this.sex = sex;
  }

  public Set<EventsCalifications> getEventsCalificationses() {
    return this.eventsCalificationses;
  }

  public void setEventsCalificationses(Set<EventsCalifications> eventsCalificationses) {
    this.eventsCalificationses = eventsCalificationses;
  }

  public Set<ArtistsCalifications> getArtistsCalificationses() {
    return this.artistsCalificationses;
  }

  public void setArtistsCalificationses(Set<ArtistsCalifications> artistsCalificationses) {
    this.artistsCalificationses = artistsCalificationses;
  }

  public Set<FanaticsArtists> getFanaticsArtistses() {
    return this.fanaticsArtistses;
  }

  public void setFanaticsArtistses(Set<FanaticsArtists> fanaticsArtistses) {
    this.fanaticsArtistses = fanaticsArtistses;
  }

  public Set<DiscsCalifications> getDiscsCalificationses() {
    return this.discsCalificationses;
  }

  public void setDiscsCalificationses(Set<DiscsCalifications> discsCalificationses) {
    this.discsCalificationses = discsCalificationses;
  }

}
