package myfan.data.models;
// Generated Jun 17, 2016 12:28:37 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * FanaticsArtistsId generated by hbm2java
 */
public class FanaticsArtistsId implements java.io.Serializable {

  private int fanaticId;
  private int artistId;

  public FanaticsArtistsId() {
  }

  public FanaticsArtistsId(int fanaticId, int artistId) {
    this.fanaticId = fanaticId;
    this.artistId = artistId;
  }

  public int getFanaticId() {
    return this.fanaticId;
  }

  public void setFanaticId(int fanaticId) {
    this.fanaticId = fanaticId;
  }

  public int getArtistId() {
    return this.artistId;
  }

  public void setArtistId(int artistId) {
    this.artistId = artistId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof FanaticsArtistsId))
      return false;
    FanaticsArtistsId castOther = (FanaticsArtistsId) other;

    return (this.getFanaticId() == castOther.getFanaticId()) && (this.getArtistId() == castOther.getArtistId());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getFanaticId();
    result = 37 * result + this.getArtistId();
    return result;
  }

}
