package myfan.data.models;
// Generated Jun 13, 2016 1:18:21 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Fanatics generated by hbm2java
 */
public class Fanatics implements java.io.Serializable {

  private Integer fanaticId;
  private Users users;
  private boolean sex;
  private Set eventsCalificationses = new HashSet(0);
  private Set artistsCalificationses = new HashSet(0);
  private Set discsCalificationses = new HashSet(0);

  public Fanatics() {
  }

  public Fanatics(Users users, boolean sex) {
    this.users = users;
    this.sex = sex;
  }

  public Fanatics(Users users, boolean sex, Set eventsCalificationses, Set artistsCalificationses,
      Set discsCalificationses) {
    this.users = users;
    this.sex = sex;
    this.eventsCalificationses = eventsCalificationses;
    this.artistsCalificationses = artistsCalificationses;
    this.discsCalificationses = discsCalificationses;
  }

  public Integer getFanaticId() {
    return this.fanaticId;
  }

  public void setFanaticId(Integer fanaticId) {
    this.fanaticId = fanaticId;
  }

  public Users getUsers() {
    return this.users;
  }

  public void setUsers(Users users) {
    this.users = users;
  }

  public boolean isSex() {
    return this.sex;
  }

  public void setSex(boolean sex) {
    this.sex = sex;
  }

  public Set getEventsCalificationses() {
    return this.eventsCalificationses;
  }

  public void setEventsCalificationses(Set eventsCalificationses) {
    this.eventsCalificationses = eventsCalificationses;
  }

  public Set getArtistsCalificationses() {
    return this.artistsCalificationses;
  }

  public void setArtistsCalificationses(Set artistsCalificationses) {
    this.artistsCalificationses = artistsCalificationses;
  }

  public Set getDiscsCalificationses() {
    return this.discsCalificationses;
  }

  public void setDiscsCalificationses(Set discsCalificationses) {
    this.discsCalificationses = discsCalificationses;
  }

}
