package myfan.data.models;
// Generated Jun 17, 2016 12:28:37 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * FanaticsArtists generated by hbm2java
 */
public class FanaticsArtists implements java.io.Serializable {

  private FanaticsArtistsId id;
  private Artists artists;
  private Fanatics fanatics;

  public FanaticsArtists() {
  }

  public FanaticsArtists(FanaticsArtistsId id, Artists artists, Fanatics fanatics) {
    this.id = id;
    this.artists = artists;
    this.fanatics = fanatics;
  }

  public FanaticsArtistsId getId() {
    return this.id;
  }

  public void setId(FanaticsArtistsId id) {
    this.id = id;
  }

  public Artists getArtists() {
    return this.artists;
  }

  public void setArtists(Artists artists) {
    this.artists = artists;
  }

  public Fanatics getFanatics() {
    return this.fanatics;
  }

  public void setFanatics(Fanatics fanatics) {
    this.fanatics = fanatics;
  }

}
