package myfan.data.models;
// Generated Jun 13, 2016 1:18:21 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Genres generated by hbm2java
 */
public class Genres implements java.io.Serializable {

  private Integer genreId;
  private String name;
  private Set usersGenreses = new HashSet(0);
  private Set discses = new HashSet(0);

  public Genres() {
  }

  public Genres(String name) {
    this.name = name;
  }

  public Genres(String name, Set usersGenreses, Set discses) {
    this.name = name;
    this.usersGenreses = usersGenreses;
    this.discses = discses;
  }

  public Integer getGenreId() {
    return this.genreId;
  }

  public void setGenreId(Integer genreId) {
    this.genreId = genreId;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set getUsersGenreses() {
    return this.usersGenreses;
  }

  public void setUsersGenreses(Set usersGenreses) {
    this.usersGenreses = usersGenreses;
  }

  public Set getDiscses() {
    return this.discses;
  }

  public void setDiscses(Set discses) {
    this.discses = discses;
  }

}
