package myfan.data.models;
// Generated Jun 17, 2016 12:28:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Genres generated by hbm2java
 */
public class Genres implements java.io.Serializable {

  private Integer genreId;
  private String name;
  private Set<UsersGenres> usersGenreses = new HashSet<UsersGenres>(0);
  private Set<Discs> discses = new HashSet<Discs>(0);

  public Genres() {
  }

  public Genres(String name) {
    this.name = name;
  }

  public Genres(String name, Set<UsersGenres> usersGenreses, Set<Discs> discses) {
    this.name = name;
    this.usersGenreses = usersGenreses;
    this.discses = discses;
  }

  public Integer getGenreId() {
    return this.genreId;
  }

  public void setGenreId(Integer genreId) {
    this.genreId = genreId;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set<UsersGenres> getUsersGenreses() {
    return this.usersGenreses;
  }

  public void setUsersGenreses(Set<UsersGenres> usersGenreses) {
    this.usersGenreses = usersGenreses;
  }

  public Set<Discs> getDiscses() {
    return this.discses;
  }

  public void setDiscses(Set<Discs> discses) {
    this.discses = discses;
  }

}
