package myfan.data.models;
// Generated Jun 13, 2016 12:10:00 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Members generated by hbm2java
 */
public class Members implements java.io.Serializable {

  private Integer memberId;
  private Artists artists;
  private String name;
  private String instrument;

  public Members() {
  }

  public Members(Artists artists, String name, String instrument) {
    this.artists = artists;
    this.name = name;
    this.instrument = instrument;
  }

  public Integer getMemberId() {
    return this.memberId;
  }

  public void setMemberId(Integer memberId) {
    this.memberId = memberId;
  }

  public Artists getArtists() {
    return this.artists;
  }

  public void setArtists(Artists artists) {
    this.artists = artists;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getInstrument() {
    return this.instrument;
  }

  public void setInstrument(String instrument) {
    this.instrument = instrument;
  }

}
