package myfan.data.models;
// Generated Jun 13, 2016 1:18:21 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

  private Integer newsId;
  private Artists artists;
  private String tittle;
  private String content;
  private Date date;

  public News() {
  }

  public News(Artists artists, String tittle, String content, Date date) {
    this.artists = artists;
    this.tittle = tittle;
    this.content = content;
    this.date = date;
  }

  public Integer getNewsId() {
    return this.newsId;
  }

  public void setNewsId(Integer newsId) {
    this.newsId = newsId;
  }

  public Artists getArtists() {
    return this.artists;
  }

  public void setArtists(Artists artists) {
    this.artists = artists;
  }

  public String getTittle() {
    return this.tittle;
  }

  public void setTittle(String tittle) {
    this.tittle = tittle;
  }

  public String getContent() {
    return this.content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Date getDate() {
    return this.date;
  }

  public void setDate(Date date) {
    this.date = date;
  }

}
