package myfan.data.models;
// Generated Jun 17, 2016 12:28:37 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Songs generated by hbm2java
 */
public class Songs implements java.io.Serializable {

  private Integer songId;
  private Discs discs;
  private String name;
  private String duration;
  private boolean state;
  private String videoLink;
  private String limitation;

  public Songs() {
  }

  public Songs(Discs discs, String name, String duration, boolean state) {
    this.discs = discs;
    this.name = name;
    this.duration = duration;
    this.state = state;
  }

  public Songs(Discs discs, String name, String duration, boolean state, String videoLink, String limitation) {
    this.discs = discs;
    this.name = name;
    this.duration = duration;
    this.state = state;
    this.videoLink = videoLink;
    this.limitation = limitation;
  }

  public Integer getSongId() {
    return this.songId;
  }

  public void setSongId(Integer songId) {
    this.songId = songId;
  }

  public Discs getDiscs() {
    return this.discs;
  }

  public void setDiscs(Discs discs) {
    this.discs = discs;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getDuration() {
    return this.duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public boolean isState() {
    return this.state;
  }

  public void setState(boolean state) {
    this.state = state;
  }

  public String getVideoLink() {
    return this.videoLink;
  }

  public void setVideoLink(String videoLink) {
    this.videoLink = videoLink;
  }

  public String getLimitation() {
    return this.limitation;
  }

  public void setLimitation(String limitation) {
    this.limitation = limitation;
  }

}
