package myfan.data.models;
// Generated May 29, 2016 3:56:57 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Ubications generated by hbm2java
 */
public class Ubications implements java.io.Serializable {

  private int ubicationId;
  private String name;
  private Set eventses = new HashSet(0);
  private Set userses = new HashSet(0);

  public Ubications() {
  }

  public Ubications(int ubicationId, String name) {
    this.ubicationId = ubicationId;
    this.name = name;
  }

  public Ubications(int ubicationId, String name, Set eventses, Set userses) {
    this.ubicationId = ubicationId;
    this.name = name;
    this.eventses = eventses;
    this.userses = userses;
  }

  public int getUbicationId() {
    return this.ubicationId;
  }

  public void setUbicationId(int ubicationId) {
    this.ubicationId = ubicationId;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set getEventses() {
    return this.eventses;
  }

  public void setEventses(Set eventses) {
    this.eventses = eventses;
  }

  public Set getUserses() {
    return this.userses;
  }

  public void setUserses(Set userses) {
    this.userses = userses;
  }

}
