package myfan.data.models;
// Generated Jun 17, 2016 12:28:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Ubications generated by hbm2java
 */
public class Ubications implements java.io.Serializable {

  private Integer ubicationId;
  private String name;
  private Set<Events> eventses = new HashSet<Events>(0);
  private Set<Users> userses = new HashSet<Users>(0);

  public Ubications() {
  }

  public Ubications(String name) {
    this.name = name;
  }

  public Ubications(String name, Set<Events> eventses, Set<Users> userses) {
    this.name = name;
    this.eventses = eventses;
    this.userses = userses;
  }

  public Integer getUbicationId() {
    return this.ubicationId;
  }

  public void setUbicationId(Integer ubicationId) {
    this.ubicationId = ubicationId;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set<Events> getEventses() {
    return this.eventses;
  }

  public void setEventses(Set<Events> eventses) {
    this.eventses = eventses;
  }

  public Set<Users> getUserses() {
    return this.userses;
  }

  public void setUserses(Set<Users> userses) {
    this.userses = userses;
  }

}
