package myfan.data.models;
// Generated Jun 13, 2016 12:10:00 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * UsersGenres generated by hbm2java
 */
public class UsersGenres implements java.io.Serializable {

  private UsersGenresId id;
  private Genres genres;
  private Users users;

  public UsersGenres() {
  }

  public UsersGenres(UsersGenresId id, Genres genres, Users users) {
    this.id = id;
    this.genres = genres;
    this.users = users;
  }

  public UsersGenresId getId() {
    return this.id;
  }

  public void setId(UsersGenresId id) {
    this.id = id;
  }

  public Genres getGenres() {
    return this.genres;
  }

  public void setGenres(Genres genres) {
    this.genres = genres;
  }

  public Users getUsers() {
    return this.users;
  }

  public void setUsers(Users users) {
    this.users = users;
  }

}
