package myfan.data.models;
// Generated Jun 13, 2016 12:10:00 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * UsersGenresId generated by hbm2java
 */
public class UsersGenresId implements java.io.Serializable {

  private int idUser;
  private int idGenre;

  public UsersGenresId() {
  }

  public UsersGenresId(int idUser, int idGenre) {
    this.idUser = idUser;
    this.idGenre = idGenre;
  }

  public int getIdUser() {
    return this.idUser;
  }

  public void setIdUser(int idUser) {
    this.idUser = idUser;
  }

  public int getIdGenre() {
    return this.idGenre;
  }

  public void setIdGenre(int idGenre) {
    this.idGenre = idGenre;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof UsersGenresId))
      return false;
    UsersGenresId castOther = (UsersGenresId) other;

    return (this.getIdUser() == castOther.getIdUser()) && (this.getIdGenre() == castOther.getIdGenre());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getIdUser();
    result = 37 * result + this.getIdGenre();
    return result;
  }

}
