package myfan.data.models;
// Generated Jun 13, 2016 1:18:21 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

  private Integer userId;
  private Ubications ubications;
  private UsersRoles usersRoles;
  private String username;
  private String password;
  private String name;
  private String image;
  private Date creationDate;
  private Date birthday;
  private Set usersGenreses = new HashSet(0);
  private Set artistses = new HashSet(0);
  private Set fanaticses = new HashSet(0);

  public Users() {
  }

  public Users(Ubications ubications, UsersRoles usersRoles, String username, String password, String name,
      Date creationDate, Date birthday) {
    this.ubications = ubications;
    this.usersRoles = usersRoles;
    this.username = username;
    this.password = password;
    this.name = name;
    this.creationDate = creationDate;
    this.birthday = birthday;
  }

  public Users(Ubications ubications, UsersRoles usersRoles, String username, String password, String name,
      String image, Date creationDate, Date birthday, Set usersGenreses, Set artistses, Set fanaticses) {
    this.ubications = ubications;
    this.usersRoles = usersRoles;
    this.username = username;
    this.password = password;
    this.name = name;
    this.image = image;
    this.creationDate = creationDate;
    this.birthday = birthday;
    this.usersGenreses = usersGenreses;
    this.artistses = artistses;
    this.fanaticses = fanaticses;
  }

  public Integer getUserId() {
    return this.userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public Ubications getUbications() {
    return this.ubications;
  }

  public void setUbications(Ubications ubications) {
    this.ubications = ubications;
  }

  public UsersRoles getUsersRoles() {
    return this.usersRoles;
  }

  public void setUsersRoles(UsersRoles usersRoles) {
    this.usersRoles = usersRoles;
  }

  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getImage() {
    return this.image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public Date getCreationDate() {
    return this.creationDate;
  }

  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }

  public Date getBirthday() {
    return this.birthday;
  }

  public void setBirthday(Date birthday) {
    this.birthday = birthday;
  }

  public Set getUsersGenreses() {
    return this.usersGenreses;
  }

  public void setUsersGenreses(Set usersGenreses) {
    this.usersGenreses = usersGenreses;
  }

  public Set getArtistses() {
    return this.artistses;
  }

  public void setArtistses(Set artistses) {
    this.artistses = artistses;
  }

  public Set getFanaticses() {
    return this.fanaticses;
  }

  public void setFanaticses(Set fanaticses) {
    this.fanaticses = fanaticses;
  }

}
