package myfan.models;
// Generated May 28, 2016 11:43:26 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Administrators generated by hbm2java
 */
public class Administrators implements java.io.Serializable {

  private int administratorId;
  private String login;
  private String password;

  public Administrators() {
  }

  public Administrators(int administratorId, String login, String password) {
    this.administratorId = administratorId;
    this.login = login;
    this.password = password;
  }

  public int getAdministratorId() {
    return this.administratorId;
  }

  public void setAdministratorId(int administratorId) {
    this.administratorId = administratorId;
  }

  public String getLogin() {
    return this.login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

}
