package myfan.models;
// Generated May 28, 2016 11:43:26 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Artists generated by hbm2java
 */
public class Artists implements java.io.Serializable {

  private int artistId;
  private Genres genres;
  private Ubications ubications;
  private String name;
  private String login;
  private String password;
  private String image;
  private int followers;
  private Set artistsCalificationses = new HashSet(0);
  private Set newses = new HashSet(0);
  private Set memberses = new HashSet(0);
  private Set eventses = new HashSet(0);

  public Artists() {
  }

  public Artists(int artistId, Genres genres, Ubications ubications, String name, String login, String password,
      int followers) {
    this.artistId = artistId;
    this.genres = genres;
    this.ubications = ubications;
    this.name = name;
    this.login = login;
    this.password = password;
    this.followers = followers;
  }

  public Artists(int artistId, Genres genres, Ubications ubications, String name, String login, String password,
      String image, int followers, Set artistsCalificationses, Set newses, Set memberses, Set eventses) {
    this.artistId = artistId;
    this.genres = genres;
    this.ubications = ubications;
    this.name = name;
    this.login = login;
    this.password = password;
    this.image = image;
    this.followers = followers;
    this.artistsCalificationses = artistsCalificationses;
    this.newses = newses;
    this.memberses = memberses;
    this.eventses = eventses;
  }

  public int getArtistId() {
    return this.artistId;
  }

  public void setArtistId(int artistId) {
    this.artistId = artistId;
  }

  public Genres getGenres() {
    return this.genres;
  }

  public void setGenres(Genres genres) {
    this.genres = genres;
  }

  public Ubications getUbications() {
    return this.ubications;
  }

  public void setUbications(Ubications ubications) {
    this.ubications = ubications;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getLogin() {
    return this.login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getImage() {
    return this.image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public int getFollowers() {
    return this.followers;
  }

  public void setFollowers(int followers) {
    this.followers = followers;
  }

  public Set getArtistsCalificationses() {
    return this.artistsCalificationses;
  }

  public void setArtistsCalificationses(Set artistsCalificationses) {
    this.artistsCalificationses = artistsCalificationses;
  }

  public Set getNewses() {
    return this.newses;
  }

  public void setNewses(Set newses) {
    this.newses = newses;
  }

  public Set getMemberses() {
    return this.memberses;
  }

  public void setMemberses(Set memberses) {
    this.memberses = memberses;
  }

  public Set getEventses() {
    return this.eventses;
  }

  public void setEventses(Set eventses) {
    this.eventses = eventses;
  }

}
