package myfan.models;
// Generated May 28, 2016 11:43:26 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * ArtistsCalifications generated by hbm2java
 */
public class ArtistsCalifications implements java.io.Serializable {

  private int artistCalificationId;
  private Artists artists;
  private int calification;
  private String comment;

  public ArtistsCalifications() {
  }

  public ArtistsCalifications(int artistCalificationId, Artists artists, int calification) {
    this.artistCalificationId = artistCalificationId;
    this.artists = artists;
    this.calification = calification;
  }

  public ArtistsCalifications(int artistCalificationId, Artists artists, int calification, String comment) {
    this.artistCalificationId = artistCalificationId;
    this.artists = artists;
    this.calification = calification;
    this.comment = comment;
  }

  public int getArtistCalificationId() {
    return this.artistCalificationId;
  }

  public void setArtistCalificationId(int artistCalificationId) {
    this.artistCalificationId = artistCalificationId;
  }

  public Artists getArtists() {
    return this.artists;
  }

  public void setArtists(Artists artists) {
    this.artists = artists;
  }

  public int getCalification() {
    return this.calification;
  }

  public void setCalification(int calification) {
    this.calification = calification;
  }

  public String getComment() {
    return this.comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

}
