package myfan.models;
// Generated May 28, 2016 11:43:26 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Discs generated by hbm2java
 */
public class Discs implements java.io.Serializable {

  private int discId;
  private Genres genres;
  private int artist;
  private String name;
  private String description;
  private Date releaseYear;
  private String label;
  private Set discsCalificationses = new HashSet(0);
  private Set songses = new HashSet(0);

  public Discs() {
  }

  public Discs(int discId, Genres genres, int artist, String name, String description, Date releaseYear) {
    this.discId = discId;
    this.genres = genres;
    this.artist = artist;
    this.name = name;
    this.description = description;
    this.releaseYear = releaseYear;
  }

  public Discs(int discId, Genres genres, int artist, String name, String description, Date releaseYear, String label,
      Set discsCalificationses, Set songses) {
    this.discId = discId;
    this.genres = genres;
    this.artist = artist;
    this.name = name;
    this.description = description;
    this.releaseYear = releaseYear;
    this.label = label;
    this.discsCalificationses = discsCalificationses;
    this.songses = songses;
  }

  public int getDiscId() {
    return this.discId;
  }

  public void setDiscId(int discId) {
    this.discId = discId;
  }

  public Genres getGenres() {
    return this.genres;
  }

  public void setGenres(Genres genres) {
    this.genres = genres;
  }

  public int getArtist() {
    return this.artist;
  }

  public void setArtist(int artist) {
    this.artist = artist;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Date getReleaseYear() {
    return this.releaseYear;
  }

  public void setReleaseYear(Date releaseYear) {
    this.releaseYear = releaseYear;
  }

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Set getDiscsCalificationses() {
    return this.discsCalificationses;
  }

  public void setDiscsCalificationses(Set discsCalificationses) {
    this.discsCalificationses = discsCalificationses;
  }

  public Set getSongses() {
    return this.songses;
  }

  public void setSongses(Set songses) {
    this.songses = songses;
  }

}
