package myfan.models;
// Generated May 29, 2016 3:37:51 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * EventsCalifications generated by hbm2java
 */
public class EventsCalifications implements java.io.Serializable {

  private int eventCalificationId;
  private Events events;
  private int calification;
  private String comment;

  public EventsCalifications() {
  }

  public EventsCalifications(int eventCalificationId, Events events, int calification) {
    this.eventCalificationId = eventCalificationId;
    this.events = events;
    this.calification = calification;
  }

  public EventsCalifications(int eventCalificationId, Events events, int calification, String comment) {
    this.eventCalificationId = eventCalificationId;
    this.events = events;
    this.calification = calification;
    this.comment = comment;
  }

  public int getEventCalificationId() {
    return this.eventCalificationId;
  }

  public void setEventCalificationId(int eventCalificationId) {
    this.eventCalificationId = eventCalificationId;
  }

  public Events getEvents() {
    return this.events;
  }

  public void setEvents(Events events) {
    this.events = events;
  }

  public int getCalification() {
    return this.calification;
  }

  public void setCalification(int calification) {
    this.calification = calification;
  }

  public String getComment() {
    return this.comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

}
