package myfan.models;
// Generated May 28, 2016 11:43:26 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fanatics generated by hbm2java
 */
public class Fanatics implements java.io.Serializable {

  private int fanaticId;
  private Ubications ubications;
  private String name;
  private Date birthday;
  private boolean sex;
  private String username;
  private String password;
  private Date creationDate;
  private String image;
  private Set fanaticsGenreses = new HashSet(0);

  public Fanatics() {
  }

  public Fanatics(int fanaticId, Ubications ubications, String name, Date birthday, boolean sex, String username,
      String password, Date creationDate) {
    this.fanaticId = fanaticId;
    this.ubications = ubications;
    this.name = name;
    this.birthday = birthday;
    this.sex = sex;
    this.username = username;
    this.password = password;
    this.creationDate = creationDate;
  }

  public Fanatics(int fanaticId, Ubications ubications, String name, Date birthday, boolean sex, String username,
      String password, Date creationDate, String image, Set fanaticsGenreses) {
    this.fanaticId = fanaticId;
    this.ubications = ubications;
    this.name = name;
    this.birthday = birthday;
    this.sex = sex;
    this.username = username;
    this.password = password;
    this.creationDate = creationDate;
    this.image = image;
    this.fanaticsGenreses = fanaticsGenreses;
  }

  public int getFanaticId() {
    return this.fanaticId;
  }

  public void setFanaticId(int fanaticId) {
    this.fanaticId = fanaticId;
  }

  public Ubications getUbications() {
    return this.ubications;
  }

  public void setUbications(Ubications ubications) {
    this.ubications = ubications;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Date getBirthday() {
    return this.birthday;
  }

  public void setBirthday(Date birthday) {
    this.birthday = birthday;
  }

  public boolean isSex() {
    return this.sex;
  }

  public void setSex(boolean sex) {
    this.sex = sex;
  }

  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public Date getCreationDate() {
    return this.creationDate;
  }

  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }

  public String getImage() {
    return this.image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public Set getFanaticsGenreses() {
    return this.fanaticsGenreses;
  }

  public void setFanaticsGenreses(Set fanaticsGenreses) {
    this.fanaticsGenreses = fanaticsGenreses;
  }

}
