package myfan.models;
// Generated May 29, 2016 3:37:51 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fanatics generated by hbm2java
 */
public class Fanatics implements java.io.Serializable {

  private int fanaticId;
  private Users users;
  private Date birthday;
  private boolean sex;
  private Set fanaticsGenreses = new HashSet(0);

  public Fanatics() {
  }

  public Fanatics(int fanaticId, Users users, Date birthday, boolean sex) {
    this.fanaticId = fanaticId;
    this.users = users;
    this.birthday = birthday;
    this.sex = sex;
  }

  public Fanatics(int fanaticId, Users users, Date birthday, boolean sex, Set fanaticsGenreses) {
    this.fanaticId = fanaticId;
    this.users = users;
    this.birthday = birthday;
    this.sex = sex;
    this.fanaticsGenreses = fanaticsGenreses;
  }

  public int getFanaticId() {
    return this.fanaticId;
  }

  public void setFanaticId(int fanaticId) {
    this.fanaticId = fanaticId;
  }

  public Users getUsers() {
    return this.users;
  }

  public void setUsers(Users users) {
    this.users = users;
  }

  public Date getBirthday() {
    return this.birthday;
  }

  public void setBirthday(Date birthday) {
    this.birthday = birthday;
  }

  public boolean isSex() {
    return this.sex;
  }

  public void setSex(boolean sex) {
    this.sex = sex;
  }

  public Set getFanaticsGenreses() {
    return this.fanaticsGenreses;
  }

  public void setFanaticsGenreses(Set fanaticsGenreses) {
    this.fanaticsGenreses = fanaticsGenreses;
  }

}
