package myfan.models;
// Generated May 29, 2016 3:37:51 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Genres generated by hbm2java
 */
public class Genres implements java.io.Serializable {

  private int genreId;
  private String name;
  private FanaticsGenres fanaticsGenres;
  private Set discses = new HashSet(0);
  private Set artistses = new HashSet(0);

  public Genres() {
  }

  public Genres(int genreId, String name) {
    this.genreId = genreId;
    this.name = name;
  }

  public Genres(int genreId, String name, FanaticsGenres fanaticsGenres, Set discses, Set artistses) {
    this.genreId = genreId;
    this.name = name;
    this.fanaticsGenres = fanaticsGenres;
    this.discses = discses;
    this.artistses = artistses;
  }

  public int getGenreId() {
    return this.genreId;
  }

  public void setGenreId(int genreId) {
    this.genreId = genreId;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FanaticsGenres getFanaticsGenres() {
    return this.fanaticsGenres;
  }

  public void setFanaticsGenres(FanaticsGenres fanaticsGenres) {
    this.fanaticsGenres = fanaticsGenres;
  }

  public Set getDiscses() {
    return this.discses;
  }

  public void setDiscses(Set discses) {
    this.discses = discses;
  }

  public Set getArtistses() {
    return this.artistses;
  }

  public void setArtistses(Set artistses) {
    this.artistses = artistses;
  }

}
