package myfan.models;
// Generated May 29, 2016 3:37:51 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Members generated by hbm2java
 */
public class Members implements java.io.Serializable {

  private int memberId;
  private Artists artists;
  private String name;
  private String instrument;

  public Members() {
  }

  public Members(int memberId, Artists artists, String name, String instrument) {
    this.memberId = memberId;
    this.artists = artists;
    this.name = name;
    this.instrument = instrument;
  }

  public int getMemberId() {
    return this.memberId;
  }

  public void setMemberId(int memberId) {
    this.memberId = memberId;
  }

  public Artists getArtists() {
    return this.artists;
  }

  public void setArtists(Artists artists) {
    this.artists = artists;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getInstrument() {
    return this.instrument;
  }

  public void setInstrument(String instrument) {
    this.instrument = instrument;
  }

}
