package myfan.models;
// Generated May 28, 2016 11:43:26 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Ubications generated by hbm2java
 */
public class Ubications implements java.io.Serializable {

  private int ubicationId;
  private String name;
  private Set artistses = new HashSet(0);
  private Set fanaticses = new HashSet(0);
  private Set eventses = new HashSet(0);

  public Ubications() {
  }

  public Ubications(int ubicationId, String name) {
    this.ubicationId = ubicationId;
    this.name = name;
  }

  public Ubications(int ubicationId, String name, Set artistses, Set fanaticses, Set eventses) {
    this.ubicationId = ubicationId;
    this.name = name;
    this.artistses = artistses;
    this.fanaticses = fanaticses;
    this.eventses = eventses;
  }

  public int getUbicationId() {
    return this.ubicationId;
  }

  public void setUbicationId(int ubicationId) {
    this.ubicationId = ubicationId;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set getArtistses() {
    return this.artistses;
  }

  public void setArtistses(Set artistses) {
    this.artistses = artistses;
  }

  public Set getFanaticses() {
    return this.fanaticses;
  }

  public void setFanaticses(Set fanaticses) {
    this.fanaticses = fanaticses;
  }

  public Set getEventses() {
    return this.eventses;
  }

  public void setEventses(Set eventses) {
    this.eventses = eventses;
  }

}
