package myfest.models;
// Generated Jun 14, 2016 9:46:17 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * ArtistsgenresId generated by hbm2java
 */
public class ArtistsgenresId implements java.io.Serializable {

  private int artistId;
  private int gendeId;

  public ArtistsgenresId() {
  }

  public ArtistsgenresId(int artistId, int gendeId) {
    this.artistId = artistId;
    this.gendeId = gendeId;
  }

  public int getArtistId() {
    return this.artistId;
  }

  public void setArtistId(int artistId) {
    this.artistId = artistId;
  }

  public int getGendeId() {
    return this.gendeId;
  }

  public void setGendeId(int gendeId) {
    this.gendeId = gendeId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof ArtistsgenresId))
      return false;
    ArtistsgenresId castOther = (ArtistsgenresId) other;

    return (this.getArtistId() == castOther.getArtistId()) && (this.getGendeId() == castOther.getGendeId());
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + this.getArtistId();
    result = 37 * result + this.getGendeId();
    return result;
  }

}
