package myfest.models;
// Generated Jun 14, 2016 9:46:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Concertsscores generated by hbm2java
 */
public class Concertsscores implements java.io.Serializable {

  private int concertScoresId;
  private int score;
  private int voters;
  private int commentAmount;
  private Set<Artists> artistses = new HashSet<Artists>(0);

  public Concertsscores() {
  }

  public Concertsscores(int concertScoresId, int score, int voters, int commentAmount) {
    this.concertScoresId = concertScoresId;
    this.score = score;
    this.voters = voters;
    this.commentAmount = commentAmount;
  }

  public Concertsscores(int concertScoresId, int score, int voters, int commentAmount, Set<Artists> artistses) {
    this.concertScoresId = concertScoresId;
    this.score = score;
    this.voters = voters;
    this.commentAmount = commentAmount;
    this.artistses = artistses;
  }

  public int getConcertScoresId() {
    return this.concertScoresId;
  }

  public void setConcertScoresId(int concertScoresId) {
    this.concertScoresId = concertScoresId;
  }

  public int getScore() {
    return this.score;
  }

  public void setScore(int score) {
    this.score = score;
  }

  public int getVoters() {
    return this.voters;
  }

  public void setVoters(int voters) {
    this.voters = voters;
  }

  public int getCommentAmount() {
    return this.commentAmount;
  }

  public void setCommentAmount(int commentAmount) {
    this.commentAmount = commentAmount;
  }

  public Set<Artists> getArtistses() {
    return this.artistses;
  }

  public void setArtistses(Set<Artists> artistses) {
    this.artistses = artistses;
  }

}
