package myfest.models;
// Generated Jun 14, 2016 9:46:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Musicalgenres generated by hbm2java
 */
public class Musicalgenres implements java.io.Serializable {

  private int musicalGenreId;
  private String genreName;
  private Set<Artistsgenres> artistsgenreses = new HashSet<Artistsgenres>(0);

  public Musicalgenres() {
  }

  public Musicalgenres(int musicalGenreId, String genreName) {
    this.musicalGenreId = musicalGenreId;
    this.genreName = genreName;
  }

  public Musicalgenres(int musicalGenreId, String genreName, Set<Artistsgenres> artistsgenreses) {
    this.musicalGenreId = musicalGenreId;
    this.genreName = genreName;
    this.artistsgenreses = artistsgenreses;
  }

  public int getMusicalGenreId() {
    return this.musicalGenreId;
  }

  public void setMusicalGenreId(int musicalGenreId) {
    this.musicalGenreId = musicalGenreId;
  }

  public String getGenreName() {
    return this.genreName;
  }

  public void setGenreName(String genreName) {
    this.genreName = genreName;
  }

  public Set<Artistsgenres> getArtistsgenreses() {
    return this.artistsgenreses;
  }

  public void setArtistsgenreses(Set<Artistsgenres> artistsgenreses) {
    this.artistsgenreses = artistsgenreses;
  }

}
