package myfest.models;
// Generated Jun 14, 2016 9:46:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Twittermentions generated by hbm2java
 */
public class Twittermentions implements java.io.Serializable {

  private int twitterMentionId;
  private Artists artists;
  private Date dateTime;

  public Twittermentions() {
  }

  public Twittermentions(int twitterMentionId, Artists artists, Date dateTime) {
    this.twitterMentionId = twitterMentionId;
    this.artists = artists;
    this.dateTime = dateTime;
  }

  public int getTwitterMentionId() {
    return this.twitterMentionId;
  }

  public void setTwitterMentionId(int twitterMentionId) {
    this.twitterMentionId = twitterMentionId;
  }

  public Artists getArtists() {
    return this.artists;
  }

  public void setArtists(Artists artists) {
    this.artists = artists;
  }

  public Date getDateTime() {
    return this.dateTime;
  }

  public void setDateTime(Date dateTime) {
    this.dateTime = dateTime;
  }

}
